Fellow         VERB
Citizens       PROPN
of             VERB
the            ADJ
Senate         PROPN
and            VERB
the            VERB
House          PROPN
of             NOUN
Representatives               NOUN
:              NOUN
               NUM

Among          ADP
the            NOUN
vicissitudes   NOUN
incident       NOUN
to             NOUN
life           VERB
,              NOUN
no             NOUN
event          NOUN
could          AUX
have           VERB
filled         VERB
me             NOUN
with           NOUN
               NOUN
greater        ADJ
anxieties      NOUN
than           NOUN
that           PRON
of             NOUN
which          NOUN
the            NOUN
notification   NOUN
was            NOUN
transmitted    VERB
by             ADP
your           NOUN
               NOUN
order          NOUN
,              NOUN
and            NOUN
received       VERB
on             VERB
the            NOUN
fourteenth     ADJ
day            NOUN
of             VERB
the            NOUN
present        ADJ
month          NOUN
.              NOUN

On             ADP
the            VERB
one            NUM
hand           NOUN
,              NOUN
               NOUN
I              PROPN
was            VERB
summoned       VERB
by             ADP
my             ADJ
Country        PROPN
,              NOUN
whose          VERB
voice          NOUN
I              PROPN
can            VERB
never          ADV
hear           VERB
but            CCONJ
with           VERB
veneration     NOUN
               NOUN
and            NOUN
love           NOUN
,              NOUN
from           VERB
a              NOUN
retreat        NOUN
which          PRON
I              PROPN
had            VERB
chosen         VERB
with           ADV
the            NOUN
fondest        ADJ
predilection   NOUN
,              NOUN
and            NOUN
,              NOUN
               VERB
in             NOUN
my             NOUN
flattering     NOUN
hopes          NOUN
,              NOUN
with           NOUN
an             ADJ
immutable      ADJ
decision       NOUN
,              NOUN
as             SCONJ
the            NOUN
asylum         NOUN
of             NOUN
my             NOUN
declining      NOUN
               NUM
years          NOUN
:              VERB
a              ADJ
retreat        NOUN
which          PRON
was            NOUN
rendered       VERB
every          NOUN
day            ADV
more           ADV
necessary      ADJ
as             NOUN
well           ADV
as             NOUN
more           ADJ
               NOUN
dear           NOUN
to             VERB
me             PRON
,              NOUN
by             ADP
the            NOUN
addition       NOUN
of             NOUN
habit          NOUN
to             NOUN
inclination    NOUN
,              NOUN
and            NOUN
of             NOUN
frequent       NOUN
interruptions  NOUN
               NOUN
in             NOUN
my             NOUN
health         NOUN
to             ADP
the            VERB
gradual        ADJ
waste          NOUN
committed      VERB
on             NOUN
it             NOUN
by             ADP
time           NOUN
.              NOUN

On             ADP
the            NOUN
other          ADJ
hand           NOUN
,              NOUN
               VERB
the            NOUN
magnitude      NOUN
and            NOUN
difficulty     NOUN
of             VERB
the            NOUN
trust          NOUN
to             NOUN
which          PRON
the            NOUN
voice          NOUN
of             NOUN
my             ADJ
Country        PROPN
called         VERB
               VERB
me             NOUN
,              NOUN
being          VERB
sufficient     VERB
to             NOUN
awaken         VERB
in             VERB
the            NOUN
wisest         ADJ
and            NUM
most           ADV
experienced    VERB
of             VERB
her            NOUN
citizens       NOUN
,              NOUN
               VERB
a              NOUN
distrustful    ADJ
scrutiny       NOUN
into           ADP
his            NOUN
qualification  NOUN
,              NOUN
could          AUX
not            VERB
but            CCONJ
overwhelm      VERB
with           NOUN
               NOUN
dispondence    NOUN
,              VERB
one            NUM
,              NOUN
who            PRON
,              VERB
inheriting     VERB
inferior       ADJ
endowments     NOUN
from           NOUN
nature         NOUN
and            NOUN
unpractised    VERB
               NOUN
in             VERB
the            ADJ
duties         NOUN
of             NOUN
civil          NOUN
administration NOUN
,              NOUN
ought          VERB
to             NOUN
be             VERB
peculiarly     ADV
conscious      ADJ
of             NOUN
his            NOUN
               NOUN
own            NOUN
deficencies    NOUN
.              NOUN

In             ADP
this           ADJ
conflict       NOUN
of             NOUN
emotions       NOUN
,              NOUN
all            VERB
I              PROPN
dare           VERB
aver           ADV
,              NOUN
is             ADV
,              ADJ
that           SCONJ
it             NOUN
               VERB
has            NOUN
been           VERB
my             VERB
faithful       ADJ
study          NOUN
to             NOUN
collect        VERB
my             NOUN
duty           NOUN
from           VERB
a              NOUN
just           ADV
appreciation   NOUN
of             NOUN
every          NOUN
               NOUN
circumstance   NOUN
,              NOUN
by             ADP
which          PRON
it             NOUN
might          ADV
be             VERB
affected       VERB
.              NOUN

All            DET
I              PROPN
dare           VERB
hope           VERB
,              NOUN
is             ADV
,              ADJ
that           PRON
,              NOUN
if             VERB
in             NOUN
               NOUN
executing      VERB
this           NOUN
task           NOUN
I              PROPN
have           VERB
been           VERB
too            VERB
much           ADJ
swayed         VERB
by             ADP
a              NOUN
grateful       ADJ
remembrance    NOUN
of             NOUN
               NOUN
former         NOUN
instances      NOUN
,              NOUN
or             ADJ
by             ADP
an             ADJ
affectionate   ADJ
sensibility    NOUN
to             NOUN
this           DET
transcendent   NOUN
proof          NOUN
,              NOUN
               NOUN
of             VERB
the            ADJ
confidence     NOUN
of             NOUN
my             NOUN
fellow         ADJ
-              NOUN
citizens       NOUN
;              PUNCT
and            NOUN
have           VERB
thence         NOUN
too            NOUN
little         ADJ
consulted      VERB
               NOUN
my             NOUN
incapacity     NOUN
as             NOUN
well           ADV
as             NOUN
disinclination NOUN
for            VERB
the            NOUN
weighty        NOUN
and            NOUN
untried        VERB
cares          VERB
before         NOUN
               VERB
me             NOUN
;              PUNCT
my             NOUN
error          ADJ
will           VERB
be             VERB
palliated      VERB
by             ADP
the            NOUN
motives        NOUN
which          PRON
misled         VERB
me             NOUN
,              NOUN
and            NOUN
its            NOUN
consequences   NOUN
               NOUN
be             NOUN
judged         VERB
by             ADP
my             ADJ
Country        PROPN
,              NOUN
with           NOUN
some           NOUN
share          NOUN
of             VERB
the            NOUN
partiality     NOUN
in             NOUN
which          PRON
they           NOUN
originated     VERB
.              NOUN
               PUNCT

Such           PROPN
being          VERB
the            VERB
impressions    NOUN
under          ADP
which          PRON
I              PROPN
have           VERB
,              VERB
in             NOUN
obedience      NOUN
to             ADP
the            VERB
public         ADJ
               NOUN
summons        NOUN
,              NOUN
repaired       VERB
to             ADP
the            VERB
present        ADJ
station        NOUN
;              PUNCT
it             NOUN
would          AUX
be             VERB
peculiarly     ADV
improper       NOUN
to             NOUN
               VERB
omit           NOUN
in             NOUN
this           NOUN
first          ADJ
official       ADJ
Act            NOUN
,              NOUN
my             NOUN
fervent        NOUN
supplications  NOUN
to             NOUN
that           PRON
Almighty       PROPN
Being          PROPN
               VERB
who            PRON
rules          VERB
over           ADP
the            NOUN
Universe       PROPN
,              NOUN
who            PRON
presides       VERB
in             VERB
the            ADJ
Councils       PROPN
of             NOUN
Nations        NOUN
,              NOUN
and            NOUN
whose          VERB
               NOUN
providential   ADJ
aids           NOUN
can            ADJ
supply         NOUN
every          VERB
human          ADJ
defect         NOUN
,              NOUN
that           SCONJ
his            NOUN
benediction    NOUN
may            NOUN
consecrate     NOUN
               NOUN
to             ADP
the            VERB
liberties      NOUN
and            NOUN
happiness      NOUN
of             VERB
the            ADJ
People         PROPN
of             VERB
the            NOUN
United         PROPN
States         PROPN
,              VERB
a              NOUN
Government     NOUN
               NOUN
instituted     VERB
by             SCONJ
themselves     PRON
for            NOUN
these          DET
essential      ADJ
purposes       NOUN
:              NOUN
and            ADJ
may            NOUN
enable         VERB
every          NOUN
               NOUN
instrument     NOUN
employed       VERB
in             NOUN
its            NOUN
administration NOUN
to             NOUN
execute        VERB
with           NOUN
success        NOUN
,              VERB
the            NOUN
functions      NOUN
               NOUN
allotted       VERB
to             NOUN
his            PRON
charge         NOUN
.              NOUN

In             ADP
tendering      VERB
this           NOUN
homage         NOUN
to             ADP
the            VERB
Great          PROPN
Author         PROPN
of             NOUN
every          NOUN
               NOUN
public         ADJ
and            NOUN
private        VERB
good           NOUN
,              NOUN
I              PROPN
assure         VERB
myself         PRON
that           SCONJ
it             NOUN
expresses      VERB
your           NOUN
sentiments     NOUN
not            NOUN
               VERB
less           ADJ
than           ADJ
my             ADJ
own            ADJ
;              PUNCT
nor            NOUN
those          PRON
of             NOUN
my             NOUN
fellow         ADJ
-              NOUN
citizens       NOUN
at             NOUN
large          ADJ
,              NOUN
less           NOUN
than           ADJ
either         ADV
.              NOUN
               PUNCT

No             DET
People         PROPN
can            ADJ
be             VERB
bound          ADJ
to             NOUN
acknowledge    VERB
and            NOUN
adore          VERB
the            NOUN
invisible      ADJ
hand           NOUN
,              NOUN
which          PRON
conducts       VERB
               VERB
the            NOUN
Affairs        PROPN
of             NOUN
men            NOUN
more           ADJ
than           ADP
the            NOUN
People         PROPN
of             VERB
the            NOUN
United         PROPN
States         PROPN
.              NOUN

Every          NOUN
step           NOUN
,              NOUN
by             ADP
               NOUN
which          PRON
they           NOUN
have           VERB
advanced       VERB
to             ADP
the            VERB
character      NOUN
of             NOUN
an             ADJ
independent    ADJ
nation         NOUN
,              NOUN
seems          NOUN
to             NOUN
               VERB
have           VERB
been           NOUN
distinguished  VERB
by             ADP
some           NOUN
token          NOUN
of             NOUN
providential   ADJ
agency         NOUN
.              NOUN

And            PROPN
in             VERB
the            NOUN
important      ADJ
               NOUN
revolution     NOUN
just           ADV
accomplished   VERB
in             VERB
the            ADJ
system         NOUN
of             VERB
their          NOUN
United         PROPN
Government     NOUN
,              VERB
the            NOUN
tranquil       NOUN
               NOUN
deliberations  NOUN
and            NOUN
voluntary      ADJ
consent        NOUN
of             NOUN
so             ADV
many           ADJ
distinct       NOUN
communities    NOUN
,              NOUN
from           NOUN
which          PRON
               VERB
the            NOUN
event          NOUN
has            NOUN
resulted       VERB
,              NOUN
can            VERB
not            ADV
be             VERB
compared       VERB
with           ADV
the            NOUN
means          NOUN
by             ADP
which          PRON
most           ADJ
Governments    PROPN
               NOUN
have           NOUN
been           NOUN
established    VERB
,              NOUN
without        NOUN
some           NOUN
return         NOUN
of             NOUN
pious          ADJ
gratitude      NOUN
along          ADP
with           NOUN
an             ADJ
               NOUN
humble         ADJ
anticipation   NOUN
of             VERB
the            NOUN
future         NOUN
blessings      NOUN
which          VERB
the            NOUN
past           ADJ
seem           NOUN
to             NOUN
presage        VERB
.              NOUN
               PUNCT

These          ADJ
reflections    NOUN
,              NOUN
arising        VERB
out            ADP
of             VERB
the            NOUN
present        ADJ
crisis         NOUN
,              NOUN
have           NOUN
forced         VERB
themselves     PRON
               NOUN
too            NOUN
strongly       ADV
on             NOUN
my             NOUN
mind           NOUN
to             NOUN
be             VERB
suppressed     VERB
.              NOUN

You            NOUN
will           VERB
join           VERB
with           VERB
me             NOUN
I              PROPN
trust          VERB
in             VERB
thinking       NOUN
,              NOUN
               NOUN
that           SCONJ
there          PRON
are            NOUN
none           PRON
under          ADP
the            NOUN
influence      NOUN
of             NOUN
which          PRON
,              ADP
the            NOUN
proceedings    NOUN
of             NOUN
a              NOUN
new            ADJ
and            NOUN
               NOUN
free           NOUN
Government     NOUN
can            ADJ
more           VERB
auspiciously   ADV
commence       NOUN
.              NOUN
               PUNCT

By             ADP
the            NOUN
article        NOUN
establishing   VERB
the            NOUN
Executive      ADJ
Department     NOUN
,              NOUN
it             NOUN
is             VERB
made           ADV
the            NOUN
duty           ADJ
               NOUN
of             VERB
the            ADJ
President      NOUN
\"to           NOUN
recommend      NOUN
to             VERB
your           VERB
consideration  NOUN
,              NOUN
such           ADJ
measures       NOUN
as             NOUN
               NOUN
he             NOUN
shall          AUX
judge          NOUN
necessary      NOUN
and            ADJ
expedient.\    NOUN
"              NOUN

The            NOUN
circumstances  NOUN
under          ADP
which          DET
               NOUN
I              PROPN
now            VERB
meet           VERB
you            NOUN
,              VERB
will           VERB
acquit         VERB
me             NOUN
from           NOUN
entering       VERB
into           ADP
that           DET
subject        NOUN
,              NOUN
farther        ADV
than           ADJ
               ADJ
to             NOUN
refer          VERB
to             ADP
the            VERB
Great          PROPN
Constitutional PROPN
Charter        NOUN
under          NOUN
which          PRON
you            NOUN
are            VERB
assembled      VERB
;              PUNCT
               NOUN
and            NOUN
which          PRON
,              NOUN
in             VERB
defining       VERB
your           NOUN
powers         NOUN
,              NOUN
designates     VERB
the            NOUN
objects        NOUN
to             NOUN
which          PRON
your           NOUN
attention      NOUN
               NOUN
is             PRON
to             ADJ
be             VERB
given          ADJ
.              NOUN

It             NOUN
will           VERB
be             VERB
more           ADV
consistent     NOUN
with           NOUN
those          DET
circumstances  NOUN
,              NOUN
and            NOUN
far            ADV
               NOUN
more           ADV
congenial      ADJ
with           ADV
the            NOUN
feelings       NOUN
which          PRON
actuate        VERB
me             NOUN
,              NOUN
to             NOUN
substitute     VERB
,              NOUN
in             NOUN
place          NOUN
of             NOUN
               VERB
a              NOUN
recommendation NOUN
of             NOUN
particular     ADJ
measures       NOUN
,              VERB
the            ADJ
tribute        NOUN
that           PRON
is             NOUN
due            ADJ
to             ADP
the            NOUN
talents        NOUN
,              NOUN
               VERB
the            NOUN
rectitude      NOUN
,              NOUN
and            VERB
the            NOUN
patriotism     NOUN
which          PRON
adorn          VERB
the            NOUN
characters     NOUN
selected       VERB
to             NOUN
devise         VERB
               NOUN
and            NOUN
adopt          VERB
them           NOUN
.              NOUN

In             ADP
these          DET
honorable      ADJ
qualifications NOUN
,              NOUN
I              PROPN
behold         VERB
the            VERB
surest         ADJ
pledges        NOUN
,              NOUN
               NOUN
that           PRON
as             NOUN
on             VERB
one            NUM
side           NOUN
,              NOUN
no             NOUN
local          ADJ
prejudices     NOUN
,              NOUN
or             ADJ
attachments    NOUN
;              PUNCT
no             NOUN
seperate       NOUN
views          NOUN
,              NOUN
               NOUN
nor            CCONJ
party          NOUN
animosities    NOUN
,              NOUN
will           VERB
misdirect      VERB
the            NOUN
comprehensive  ADJ
and            NOUN
equal          ADJ
eye            NOUN
which          PRON
               NOUN
ought          NOUN
to             NOUN
watch          VERB
over           ADV
this           NOUN
great          NOUN
assemblage     NOUN
of             NOUN
communities    NOUN
and            NOUN
interests      NOUN
:              NOUN
so             ADV
,              ADJ
               INTJ
on             NOUN
another        NOUN
,              NOUN
that           SCONJ
the            NOUN
foundations    NOUN
of             NOUN
our            ADJ
National       PROPN
policy         NOUN
will           VERB
be             VERB
laid           ADJ
in             VERB
the            NOUN
               NOUN
pure           NOUN
and            NOUN
immutable      ADJ
principles     NOUN
of             NOUN
private        NOUN
morality       NOUN
;              PUNCT
and            VERB
the            NOUN
pre            NOUN
-              NOUN
eminence       NOUN
of             VERB
a              NOUN
               NOUN
free           NOUN
Government     NOUN
,              NOUN
be             NOUN
exemplified    VERB
by             SCONJ
all            ADV
the            NOUN
attributes     NOUN
which          PRON
can            NOUN
win            VERB
the            VERB
affections     ADJ
               NOUN
of             NOUN
its            NOUN
Citizens       PROPN
,              NOUN
and            VERB
command        VERB
the            NOUN
respect        NOUN
of             VERB
the            NOUN
world          NOUN
.              NOUN
               PUNCT

I              ADV
dwell          VERB
on             VERB
this           NOUN
prospect       NOUN
with           NOUN
every          NOUN
satisfaction   NOUN
which          PRON
an             ADJ
ardent         NOUN
love           NOUN
for            NOUN
               NOUN
my             NOUN
Country        PROPN
can            ADJ
inspire        VERB
:              VERB
since          NOUN
there          PRON
is             PRON
no             NOUN
truth          NOUN
more           ADJ
thoroughly     ADV
established    VERB
,              NOUN
               ADJ
than           ADJ
that           SCONJ
there          PRON
exists         VERB
in             VERB
the            NOUN
oeconomy       NOUN
and            NOUN
course         NOUN
of             NOUN
nature         NOUN
,              NOUN
an             NOUN
indissoluble   ADJ
               NOUN
union          NOUN
between        NOUN
virtue         NOUN
and            NOUN
happiness      NOUN
,              NOUN
between        NOUN
duty           NOUN
and            NOUN
advantage      NOUN
,              NOUN
between        VERB
the            NOUN
               NOUN
genuine        NOUN
maxims         NOUN
of             NOUN
an             ADJ
honest         ADJ
and            VERB
magnanimous    ADJ
policy         NOUN
,              NOUN
and            VERB
the            NOUN
solid          ADJ
rewards        NOUN
of             NOUN
               NOUN
public         ADJ
prosperity     NOUN
and            NOUN
felicity       NOUN
:              NOUN
Since          NOUN
we             NOUN
ought          VERB
to             NOUN
be             VERB
no             ADJ
less           ADV
persuaded      ADJ
that           PRON
               VERB
the            NOUN
propitious     ADJ
smiles         NOUN
of             NOUN
Heaven         PROPN
,              NOUN
can            VERB
never          ADV
be             VERB
expected       VERB
on             VERB
a              NOUN
nation         NOUN
that           PRON
disregards     NOUN
               VERB
the            NOUN
eternal        ADJ
rules          NOUN
of             NOUN
order          NOUN
and            NOUN
right          NOUN
,              NOUN
which          PRON
Heaven         PROPN
itself         PRON
has            PROPN
ordained       VERB
:              NOUN
And            NOUN
               NOUN
since          VERB
the            NOUN
preservation   NOUN
of             VERB
the            NOUN
sacred         VERB
fire           NOUN
of             NOUN
liberty        NOUN
,              NOUN
and            VERB
the            NOUN
destiny        NOUN
of             VERB
the            NOUN
               NOUN
Republican     ADJ
model          NOUN
of             NOUN
Government     NOUN
,              NOUN
are            NOUN
justly         ADV
considered     VERB
as             NOUN
deeply         ADV
,              NOUN
perhaps        ADV
as             NOUN
               NOUN
finally        ADV
staked         VERB
,              NOUN
on             VERB
the            NOUN
experiment     NOUN
entrusted      VERB
to             ADP
the            VERB
hands          NOUN
of             VERB
the            ADJ
American       ADJ
people         NOUN
.              VERB
               PUNCT

Besides        ADP
the            NOUN
ordinary       ADJ
objects        NOUN
submitted      VERB
to             VERB
your           VERB
care           NOUN
,              NOUN
it             NOUN
will           VERB
remain         VERB
with           VERB
your           NOUN
               NOUN
judgment       NOUN
to             NOUN
decide         VERB
,              NOUN
how            ADV
far            ADV
an             NOUN
exercise       NOUN
of             VERB
the            NOUN
occasional     ADJ
power          NOUN
delegated      VERB
by             SCONJ
               ADV
the            NOUN
Fifth          PROPN
article        NOUN
of             VERB
the            ADJ
Constitution   NOUN
is             NOUN
rendered       VERB
expedient      ADJ
at             VERB
the            NOUN
present        ADJ
juncture       NOUN
               NOUN
by             ADP
the            NOUN
nature         NOUN
of             NOUN
objections     NOUN
which          PRON
have           NOUN
been           NOUN
urged          VERB
against        ADP
the            NOUN
System         PROPN
,              NOUN
or             ADJ
by             SCONJ
               ADV
the            NOUN
degree         NOUN
of             NOUN
inquietude     NOUN
which          PRON
has            NOUN
given          VERB
birth          NOUN
to             VERB
them           VERB
.              NOUN

Instead        NOUN
of             NOUN
undertaking    VERB
               NOUN
particular     ADJ
recommendations               NOUN
on             NOUN
this           NOUN
subject        NOUN
,              NOUN
in             VERB
which          PRON
I              PROPN
could          AUX
be             VERB
guided         VERB
by             ADP
no             NOUN
               NOUN
lights         NOUN
derived        VERB
from           NOUN
official       ADJ
opportunities  NOUN
,              NOUN
I              PROPN
shall          AUX
again          VERB
give           ADJ
way            NOUN
to             NOUN
my             PRON
entire         NOUN
               NOUN
confidence     NOUN
in             VERB
your           NOUN
discernment    NOUN
and            NOUN
pursuit        NOUN
of             VERB
the            NOUN
public         ADJ
good           NOUN
:              PUNCT

For            INTJ
I              PROPN
assure         VERB
               VERB
myself         PRON
that           PRON
whilst         SCONJ
you            NOUN
carefully      ADV
avoid          VERB
every          NOUN
alteration     NOUN
which          PRON
might          AUX
endanger       VERB
               VERB
the            NOUN
benefits       NOUN
of             NOUN
an             ADJ
United         PROPN
and            NOUN
effective      ADJ
Government     NOUN
,              NOUN
or             ADJ
which          PRON
ought          NOUN
to             NOUN
await          VERB
               VERB
the            NOUN
future         ADJ
lessons        NOUN
of             NOUN
experience     NOUN
;              NOUN

a              VERB
reverence      NOUN
for            NOUN
the            NOUN
characteristic ADJ
rights         NOUN
               NOUN
of             NOUN
freemen        NOUN
,              NOUN
and            VERB
a              NOUN
regard         NOUN
for            NOUN
the            NOUN
public         ADJ
harmony        NOUN
,              NOUN
will           VERB
sufficiently   ADV
influence      NOUN
               NOUN

your           VERB
deliberations  NOUN
on             VERB
the            NOUN
question       NOUN
how            ADV
far            ADJ
the            NOUN
former         NOUN
can            NOUN
be             VERB
more           ADV
impregnably    ADV
               NOUN
fortified      VERB
,              NOUN
or             VERB
the            NOUN
latter         NOUN
be             NOUN
safely         ADV
and            NOUN
advantageously ADV
promoted       VERB
.              NOUN
               PUNCT

To             VERB
the            VERB
preceeding     NOUN
observations   NOUN
I              PROPN
have           VERB
one            NUM
to             NOUN
add            VERB
,              NOUN
which          PRON
will           VERB
be             VERB
most           ADV
properly       ADV
               NOUN
addressed      VERB
to             ADP
the            VERB
House          PROPN
of             NOUN
Representatives               PROPN
.              NOUN

It             NOUN
concerns       VERB
myself         PRON
,              NOUN
and            NOUN
will           VERB
therefore      VERB
               NOUN
be             NOUN
as             ADJ
brief          NOUN
as             NOUN
possible       ADJ
.              NOUN

When           ADV
I              PROPN
was            VERB
first          VERB
honoured       VERB
with           CCONJ
a              NOUN
call           NOUN
into           ADP
the            NOUN
Service        PROPN
               NOUN
of             NOUN
my             ADJ
Country        PROPN
,              NOUN
then           ADV
on             VERB
the            NOUN
eve            NOUN
of             NOUN
an             ADJ
arduous        ADJ
struggle       NOUN
for            NOUN
its            NOUN
liberties      NOUN
,              VERB
the            NOUN
               NOUN
light          NOUN
in             NOUN
which          PRON
I              PROPN
contemplated   VERB
my             VERB
duty           NOUN
required       VERB
that           SCONJ
I              PROPN
should         AUX
renounce       NOUN
every          NOUN
               NOUN
pecuniary      ADJ
compensation   NOUN
.              NOUN

From           ADV
this           NOUN
resolution     NOUN
I              PROPN
have           VERB
in             VERB
no             NOUN
instance       NOUN
departed       VERB
.              NOUN
               PUNCT

And            NOUN
being          VERB
still          ADV
under          ADP
the            NOUN
impressions    NOUN
which          PRON
produced       VERB
it             NOUN
,              SCONJ
I              PROPN
must           AUX
decline        PRON
as             NOUN
inapplicable   ADJ
               NOUN
to             NOUN
myself         VERB
,              NOUN
any            ADJ
share          NOUN
in             VERB
the            NOUN
personal       ADJ
emoluments     NOUN
,              NOUN
which          PRON
may            NOUN
be             VERB
indispensably  ADV
               NOUN
included       VERB
in             VERB
a              NOUN
permanent      NOUN
provision      NOUN
for            VERB
the            NOUN
Executive      ADJ
Department     NOUN
;              PUNCT
and            NOUN
must           NOUN
accordingly    ADV
               NOUN
pray           NOUN
that           SCONJ
the            NOUN
pecuniary      ADJ
estimates      NOUN
for            VERB
the            NOUN
Station        NOUN
in             NOUN
which          PRON
I              PROPN
am             VERB
placed         VERB
,              NOUN
may            VERB
,              VERB
               NOUN
during         ADP
my             NOUN
continuance    NOUN
in             NOUN
it             NOUN
,              AUX
be             NOUN
limited        VERB
to             NOUN
such           VERB
actual         ADJ
expenditures   NOUN
as             SCONJ
the            NOUN
public         ADJ
               NOUN
good           NOUN
may            NOUN
be             VERB
thought        ADJ
to             NOUN
require        VERB
.              NOUN
               PUNCT

Having         VERB
thus           ADV
imparted       VERB
to             NOUN
you            VERB
my             ADV
sentiments     NOUN
,              NOUN
as             NOUN
they           NOUN
have           VERB
been           NOUN
awakened       VERB
by             ADP
the            NOUN
               NOUN
occasion       NOUN
which          PRON
brings         VERB
us             NOUN
together       ADV
,              NOUN
I              PROPN
shall          AUX
take           VERB
my             NOUN
present        NOUN
leave          NOUN
;              PUNCT
but            CCONJ
not            VERB
without        NOUN
               NOUN
resorting      VERB
once           ADV
more           ADJ
to             ADP
the            VERB
benign         ADJ
parent         NOUN
of             VERB
the            NOUN
human          NOUN
race           NOUN
,              NOUN
in             NOUN
humble         ADJ
supplication   NOUN
               NOUN
that           SCONJ
since          NOUN
he             NOUN
has            VERB
been           VERB
pleased        ADJ
to             NOUN
favour         VERB
the            NOUN
American       ADJ
people         NOUN
,              VERB
with           NOUN
opportunities  NOUN
               NOUN
for            NOUN
deliberating   VERB
in             NOUN
perfect        NOUN
tranquility    NOUN
,              NOUN
and            NOUN
dispositions   NOUN
for            NOUN
deciding       VERB
with           NOUN
               NOUN
unparellelled  VERB
unanimity      NOUN
on             VERB
a              NOUN
form           NOUN
of             NOUN
Government     PROPN
,              NOUN
for            VERB
the            NOUN
security       NOUN
of             VERB
their          ADJ
Union          PROPN
,              NOUN
               ADJ
and            VERB
the            NOUN
advancement    NOUN
of             VERB
their          ADV
happiness      NOUN
;              PUNCT
so             ADV
his            ADJ
divine         NOUN
blessing       VERB
may            NOUN
be             VERB
equally        ADV
               NOUN
conspicuous    ADJ
in             VERB
the            NOUN
enlarged       VERB
views          NOUN
,              VERB
the            NOUN
temperate      NOUN
consultations  NOUN
,              NOUN
and            VERB
the            NOUN
wise           NOUN
               NOUN
measures       NOUN
on             NOUN
which          VERB
the            NOUN
success        NOUN
of             VERB
this           ADJ
Government     NOUN
must           NOUN
depend         NOUN
.              NOUN

               PUNCT

